[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "slicer_tools"
version = "v0.9.0"
authors = [
  {name="BuongiornoTexas"},
]
description = "Tools for working with 3D slicer (.3mf) files. Currently focussed on Bambu Studio."
readme = "README.md"
requires-python = ">=3.13"
keywords = [
  "3D Slicer",
  "Bambu Studio",
  "3mf comparison",
  "3D file comparison",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openpyxl",
]

[project.urls]
"Homepage" = "https://github.com/BuongiornoTexas/slicer_tools"
"Bug Tracker" = "https://github.com/BuongiornoTexas/slicer_tools/issues"